// build.rs — scan library/ at compile time and generate include_str! entries
// so that adding a .kicad_sym file requires zero Rust code changes.

use std::path::Path;

fn main() {
    let library_dir = Path::new("library");
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("builtin_library_generated.rs");

    let mut entries: Vec<(String, String)> = Vec::new();

    if let Ok(dir) = std::fs::read_dir(library_dir) {
        for lib_entry in dir.flatten() {
            let lib_path = lib_entry.path();
            if !lib_path.is_dir() {
                continue;
            }
            let lib_prefix = match lib_path.file_name().and_then(|n| n.to_str()) {
                Some(n) => n.to_string(),
                None => continue,
            };

            if let Ok(sub) = std::fs::read_dir(&lib_path) {
                for file_entry in sub.flatten() {
                    let fp = file_entry.path();
                    if fp.extension().map_or(true, |e| e != "kicad_sym") {
                        continue;
                    }

                    // Store (relative_path_from_crate_root, lib_prefix)
                    let rel = fp.strip_prefix(library_dir).unwrap_or(&fp);
                    entries.push((rel.display().to_string(), lib_prefix.clone()));
                }
            }
        }
    }

    // Deterministic ordering
    entries.sort_by(|a, b| a.0.cmp(&b.0));

    let mut code = String::new();
    code.push_str("// AUTO-GENERATED by build.rs — do not edit\n");
    code.push_str("// Lists all .kicad_sym files found under library/\n\n");
    code.push_str("pub fn builtin_entries() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");

    for (rel_path, lib_prefix) in &entries {
        let escaped_prefix = lib_prefix.replace('\\', "\\\\").replace('"', "\\\"");
        code.push_str(&format!(
            "        (\n            include_str!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/library/{}\")),\n            \"{}\",\n        ),\n",
            rel_path, escaped_prefix
        ));
    }

    code.push_str("    ]\n");
    code.push_str("}\n");

    std::fs::write(&dest_path, code)
        .expect("failed to write builtin_library_generated.rs");
}
